In [19]:
# Import Modules
import pandas as pd
from pathlib import Path

In [20]:
# Read CSV File for 2023
census_data_23 = Path("Resources/census_data_2023.csv")
census_df_23 = pd.read_csv(census_data_23)

# Display the DataFrame
census_df_23.head()

# Keep only columns that contain "Median income (dollars)!!Estimate" in their name
filtered_columns_23 = [col for col in census_df_23.columns if "Median income (dollars)!!Estimate" in col or "Label (Grouping)" in col]

# Create a new DataFrame with only the filtered columns
census_df_filtered_23 = census_df_23[filtered_columns_23]

# Check the filtered DataFrame
census_df_filtered_23.head()

# Transpose DF
census_df_filtered_t_23 = census_df_filtered_23.transpose()
census_df_filtered_t_23.columns = census_df_filtered_t_23.iloc[0]
census_df_filtered_t_23.head()

# Rename Columns by taking out extra characters
census_renamed_23 = census_df_filtered_23.rename(columns=lambda col: col.replace('!!', ''))
census_renamed_23

#transpose
census_t_23 = census_renamed_23.transpose()
census_t_23.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,2021 Median Household Income,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,Some other race,Two or more races,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
AlabamaMedian income (dollars)Estimate,NaN,"62,212",NaN,"71,058","43,339","56,971","96,502","50,596","49,533","60,127",...,"106,182","139,425",NaN,"34,218","30,366","27,918","60,997","40,543","36,374","62,028"
AlaskaMedian income (dollars)Estimate,NaN,"86,631",NaN,"93,216","60,170","60,691","97,145","97,679","101,032","76,718",...,"126,384","176,341",NaN,"56,638","54,346","46,402","98,840","60,107","47,128","109,736"
ArizonaMedian income (dollars)Estimate,NaN,"77,315",NaN,"81,415","59,504","47,592","104,805","52,442","67,687","72,904",...,"116,203","149,084",NaN,"49,360","43,752","37,735","80,137","54,347","46,116","92,026"
ArkansasMedian income (dollars)Estimate,NaN,"58,700",NaN,"62,859","35,920","65,812","79,176","67,892","62,973","60,649",...,"101,282","127,975",NaN,"33,635","29,742","26,725","52,980","38,263","34,978","61,827"

In [21]:
census_t_23[1]

Label (Grouping)                                       2021 Median Household Income
AlabamaMedian income (dollars)Estimate                                       62,212
AlaskaMedian income (dollars)Estimate                                        86,631
ArizonaMedian income (dollars)Estimate                                       77,315
ArkansasMedian income (dollars)Estimate                                      58,700
CaliforniaMedian income (dollars)Estimate                                    95,521
ColoradoMedian income (dollars)Estimate                                      92,911
ConnecticutMedian income (dollars)Estimate                                   91,665
DelawareMedian income (dollars)Estimate                                      81,361
District of ColumbiaMedian income (dollars)Estimate                         108,210
FloridaMedian income (dollars)Estimate                                       73,311
GeorgiaMedian income (dollars)Estimate                                       74,632
HawaiiMedian income (dollars)Estimate                                        95,322
IdahoMedian income (dollars)Estimate                                         74,942
IllinoisMedian income (dollars)Estimate                                      80,306
IndianaMedian income (dollars)Estimate                                       69,477
IowaMedian income (dollars)Estimate                                          71,433
KansasMedian income (dollars)Estimate                                        70,333
KentuckyMedian income (dollars)Estimate                                      61,118
LouisianaMedian income (dollars)Estimate                                     58,229
MaineMedian income (dollars)Estimate                                         73,733
MarylandMedian income (dollars)Estimate                                      98,678
MassachusettsMedian income (dollars)Estimate                                 99,858
MichiganMedian income (dollars)Estimate                                      69,183
MinnesotaMedian income (dollars)Estimate                                     85,086
MississippiMedian income (dollars)Estimate                                   54,203
MissouriMedian income (dollars)Estimate                                      68,545
MontanaMedian income (dollars)Estimate                                       70,804
NebraskaMedian income (dollars)Estimate                                      74,590
NevadaMedian income (dollars)Estimate                                        76,364
New HampshireMedian income (dollars)Estimate                                 96,838
New JerseyMedian income (dollars)Estimate                                    99,781
New MexicoMedian income (dollars)Estimate                                    62,268
New YorkMedian income (dollars)Estimate                                      82,095
North CarolinaMedian income (dollars)Estimate                                70,804
North DakotaMedian income (dollars)Estimate                                  76,525
OhioMedian income (dollars)Estimate                                          67,769
OklahomaMedian income (dollars)Estimate                                      62,138
OregonMedian income (dollars)Estimate                                        80,160
PennsylvaniaMedian income (dollars)Estimate                                  73,824
Rhode IslandMedian income (dollars)Estimate                                  84,972
South CarolinaMedian income (dollars)Estimate                                67,804
South DakotaMedian income (dollars)Estimate                                  71,810
TennesseeMedian income (dollars)Estimate                                     67,631
TexasMedian income (dollars)Estimate                                         75,780
UtahMedian income (dollars)Estimate                                          93,421
VermontMedian income (dollars)Estimate                                       81,211
VirginiaMedian income (dollars)Estimate                                      89,931
WashingtonMedian income (dollars)Estimate                                    94,605
West VirginiaMedian income (dollars)Estimate                                 55,948
WisconsinMedian income (dollars)Estimate                                     74,631
WyomingMedian income (dollars)Estimate                                       72,415
Puerto RicoMedian income (dollars)Estimate                                   25,621
Name: 1, dtype: object

In [22]:
census_23_households = census_t_23[1].reset_index()

In [23]:
census_23_households.columns = census_23_households.iloc[0]
census_23_households = census_23_households[1:]

In [24]:
census_23_households

,Label (Grouping),2021 Median Household Income
1,AlabamaMedian income (dollars)Estimate,"62,212"
2,AlaskaMedian income (dollars)Estimate,"86,631"
3,ArizonaMedian income (dollars)Estimate,"77,315"
4,ArkansasMedian income (dollars)Estimate,"58,700"
5,CaliforniaMedian income (dollars)Estimate,"95,521"
6,ColoradoMedian income (dollars)Estimate,"92,911"
7,ConnecticutMedian income (dollars)Estimate,"91,665"
8,DelawareMedian income (dollars)Estimate,"81,361"
9,District of ColumbiaMedian income (dollars)Est...,"108,210"
10,FloridaMedian income (dollars)Estimate,"73,311"
11,GeorgiaMedian income (dollars)Estimate,"74,632"
12,HawaiiMedian income (dollars)Estimate,"95,322"
13,IdahoMedian income (dollars)Estimate,"74,942"
14,IllinoisMedian income (dollars)Estimate,"80,306"
15,IndianaMedian income (dollars)Estimate,"69,477"
16,IowaMedian income (dollars)Estimate,"71,433"
17,KansasMedian income (dollars)Estimate,"70,333"
18,KentuckyMedian income (dollars)Estimate,"61,118"
19,LouisianaMedian income (dollars)Estimate,"58,229"
20,MaineMedian income (dollars)Estimate,"73,733"
21,MarylandMedian income (dollars)Estimate,"98,678"
22,MassachusettsMedian income (dollars)Estimate,"99,858"
23,MichiganMedian income (dollars)Estimate,"69,183"
24,MinnesotaMedian income (dollars)Estimate,"85,086"
25,MississippiMedian income (dollars)Estimate,"54,203"
26,MissouriMedian income (dollars)Estimate,"68,545"
27,MontanaMedian income (dollars)Estimate,"70,804"
28,NebraskaMedian income (dollars)Estimate,"74,590"
29,NevadaMedian income (dollars)Estimate,"76,364"
30,New HampshireMedian income (dollars)Estimate,"96,838"
31,New JerseyMedian income (dollars)Estimate,"99,781"
32,New MexicoMedian income (dollars)Estimate,"62,268"
33,New YorkMedian income (dollars)Estimate,"82,095"
34,North CarolinaMedian income (dollars)Estimate,"70,804"
35,North DakotaMedian income (dollars)Estimate,"76,525"
36,OhioMedian income (dollars)Estimate,"67,769"
37,OklahomaMedian income (dollars)Estimate,"62,138"
38,OregonMedian income (dollars)Estimate,"80,160"
39,PennsylvaniaMedian income (dollars)Estimate,"73,824"
40,Rhode IslandMedian income (dollars)Estimate,"84,972"
41,South CarolinaMedian income (dollars)Estimate,"67,804"
42,South DakotaMedian income (dollars)Estimate,"71,810"
43,TennesseeMedian income (dollars)Estimate,"67,631"
44,TexasMedian income (dollars)Estimate,"75,780"
45,UtahMedian income (dollars)Estimate,"93,421"
46,VermontMedian income (dollars)Estimate,"81,211"
47,VirginiaMedian income (dollars)Estimate,"89,931"
48,WashingtonMedian income (dollars)Estimate,"94,605"
49,West VirginiaMedian income (dollars)Estimate,"55,948"
50,WisconsinMedian income (dollars)Estimate,"74,631"
51,WyomingMedian income (dollars)Estimate,"72,415"
52,Puerto RicoMedian income (dollars)Estimate,"25,621"

In [25]:
# Read CSV File for 2022
census_data_22 = Path("Resources/census_data_2022.csv")
census_df_22 = pd.read_csv(census_data_22)

# Display the DataFrame
census_df_22.head()

# Keep only columns that contain "Median income (dollars)!!Estimate" in their name
filtered_columns_22 = [col for col in census_df_22.columns if "Median income (dollars)!!Estimate" in col or "Label (Grouping)" in col]

# Create a new DataFrame with only the filtered columns
census_df_filtered_22 = census_df_22[filtered_columns_22]

# Check the filtered DataFrame
census_df_filtered_22.head()

# Transpose DF
census_df_filtered_t_22 = census_df_filtered_22.transpose()
census_df_filtered_t_22.columns = census_df_filtered_t_22.iloc[0]
census_df_filtered_t_22.head()

# Rename Columns by taking out extra characters
census_renamed_22 = census_df_filtered_22.rename(columns=lambda col: col.replace('!!', ''))
census_renamed_22

#transpose
census_t_22 = census_renamed_22.transpose()
census_t_22.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,2022 Median Household Income,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,Some other race,Two or more races,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
AlabamaMedian income (dollars)Estimate,NaN,"59,674",NaN,"68,168","40,774","62,000","83,281","107,739","49,889","62,694",...,"103,776","128,218",NaN,"32,330","28,708","26,540","52,816","37,760","33,802","63,143"
AlaskaMedian income (dollars)Estimate,NaN,"88,121",NaN,"96,000","73,018","53,969","93,212","61,423","83,917","84,416",...,"120,805","160,125",NaN,"57,657","55,513","45,643","87,875","61,089","49,336","106,781"
ArizonaMedian income (dollars)Estimate,NaN,"74,568",NaN,"79,606","58,894","48,896","96,288","78,411","66,037","66,284",...,"111,107","138,258",NaN,"47,840","43,134","36,564","80,276","52,588","44,743","88,192"
ArkansasMedian income (dollars)Estimate,NaN,"55,432",NaN,"60,595","35,703","62,518","83,200","37,736","53,528","55,609",...,"95,083","124,486",NaN,"31,230","27,689","25,379","57,548","36,159","31,246","61,002"

In [26]:
census_t_22[1]

Label (Grouping)                                       2022 Median Household Income
AlabamaMedian income (dollars)Estimate                                       59,674
AlaskaMedian income (dollars)Estimate                                        88,121
ArizonaMedian income (dollars)Estimate                                       74,568
ArkansasMedian income (dollars)Estimate                                      55,432
CaliforniaMedian income (dollars)Estimate                                    91,551
ColoradoMedian income (dollars)Estimate                                      89,302
ConnecticutMedian income (dollars)Estimate                                   88,429
DelawareMedian income (dollars)Estimate                                      82,174
District of ColumbiaMedian income (dollars)Estimate                         101,027
FloridaMedian income (dollars)Estimate                                       69,303
GeorgiaMedian income (dollars)Estimate                                       72,837
HawaiiMedian income (dollars)Estimate                                        92,458
IdahoMedian income (dollars)Estimate                                         72,785
IllinoisMedian income (dollars)Estimate                                      76,708
IndianaMedian income (dollars)Estimate                                       66,785
IowaMedian income (dollars)Estimate                                          69,588
KansasMedian income (dollars)Estimate                                        68,925
KentuckyMedian income (dollars)Estimate                                      59,341
LouisianaMedian income (dollars)Estimate                                     55,416
MaineMedian income (dollars)Estimate                                         69,543
MarylandMedian income (dollars)Estimate                                      94,991
MassachusettsMedian income (dollars)Estimate                                 94,488
MichiganMedian income (dollars)Estimate                                      66,986
MinnesotaMedian income (dollars)Estimate                                     82,338
MississippiMedian income (dollars)Estimate                                   52,719
MissouriMedian income (dollars)Estimate                                      64,811
MontanaMedian income (dollars)Estimate                                       67,631
NebraskaMedian income (dollars)Estimate                                      69,597
NevadaMedian income (dollars)Estimate                                        72,333
New HampshireMedian income (dollars)Estimate                                 89,992
New JerseyMedian income (dollars)Estimate                                    96,346
New MexicoMedian income (dollars)Estimate                                    59,726
New YorkMedian income (dollars)Estimate                                      79,557
North CarolinaMedian income (dollars)Estimate                                67,481
North DakotaMedian income (dollars)Estimate                                  71,970
OhioMedian income (dollars)Estimate                                          65,720
OklahomaMedian income (dollars)Estimate                                      59,673
OregonMedian income (dollars)Estimate                                        75,657
PennsylvaniaMedian income (dollars)Estimate                                  71,798
Rhode IslandMedian income (dollars)Estimate                                  81,854
South CarolinaMedian income (dollars)Estimate                                64,115
South DakotaMedian income (dollars)Estimate                                  69,728
TennesseeMedian income (dollars)Estimate                                     65,254
TexasMedian income (dollars)Estimate                                         72,284
UtahMedian income (dollars)Estimate                                          89,168
VermontMedian income (dollars)Estimate                                       73,991
VirginiaMedian income (dollars)Estimate                                      85,873
WashingtonMedian income (dollars)Estimate                                    91,306
West VirginiaMedian income (dollars)Estimate                                 54,329
WisconsinMedian income (dollars)Estimate                                     70,996
WyomingMedian income (dollars)Estimate                                       70,042
Puerto RicoMedian income (dollars)Estimate                                   24,112
Name: 1, dtype: object

In [27]:
census_22_households = census_t_22[1].reset_index()

In [28]:
census_22_households.columns = census_22_households.iloc[0]
census_22_households = census_22_households[1:]

In [29]:
census_22_households

,Label (Grouping),2022 Median Household Income
1,AlabamaMedian income (dollars)Estimate,"59,674"
2,AlaskaMedian income (dollars)Estimate,"88,121"
3,ArizonaMedian income (dollars)Estimate,"74,568"
4,ArkansasMedian income (dollars)Estimate,"55,432"
5,CaliforniaMedian income (dollars)Estimate,"91,551"
6,ColoradoMedian income (dollars)Estimate,"89,302"
7,ConnecticutMedian income (dollars)Estimate,"88,429"
8,DelawareMedian income (dollars)Estimate,"82,174"
9,District of ColumbiaMedian income (dollars)Est...,"101,027"
10,FloridaMedian income (dollars)Estimate,"69,303"
11,GeorgiaMedian income (dollars)Estimate,"72,837"
12,HawaiiMedian income (dollars)Estimate,"92,458"
13,IdahoMedian income (dollars)Estimate,"72,785"
14,IllinoisMedian income (dollars)Estimate,"76,708"
15,IndianaMedian income (dollars)Estimate,"66,785"
16,IowaMedian income (dollars)Estimate,"69,588"
17,KansasMedian income (dollars)Estimate,"68,925"
18,KentuckyMedian income (dollars)Estimate,"59,341"
19,LouisianaMedian income (dollars)Estimate,"55,416"
20,MaineMedian income (dollars)Estimate,"69,543"
21,MarylandMedian income (dollars)Estimate,"94,991"
22,MassachusettsMedian income (dollars)Estimate,"94,488"
23,MichiganMedian income (dollars)Estimate,"66,986"
24,MinnesotaMedian income (dollars)Estimate,"82,338"
25,MississippiMedian income (dollars)Estimate,"52,719"
26,MissouriMedian income (dollars)Estimate,"64,811"
27,MontanaMedian income (dollars)Estimate,"67,631"
28,NebraskaMedian income (dollars)Estimate,"69,597"
29,NevadaMedian income (dollars)Estimate,"72,333"
30,New HampshireMedian income (dollars)Estimate,"89,992"
31,New JerseyMedian income (dollars)Estimate,"96,346"
32,New MexicoMedian income (dollars)Estimate,"59,726"
33,New YorkMedian income (dollars)Estimate,"79,557"
34,North CarolinaMedian income (dollars)Estimate,"67,481"
35,North DakotaMedian income (dollars)Estimate,"71,970"
36,OhioMedian income (dollars)Estimate,"65,720"
37,OklahomaMedian income (dollars)Estimate,"59,673"
38,OregonMedian income (dollars)Estimate,"75,657"
39,PennsylvaniaMedian income (dollars)Estimate,"71,798"
40,Rhode IslandMedian income (dollars)Estimate,"81,854"
41,South CarolinaMedian income (dollars)Estimate,"64,115"
42,South DakotaMedian income (dollars)Estimate,"69,728"
43,TennesseeMedian income (dollars)Estimate,"65,254"
44,TexasMedian income (dollars)Estimate,"72,284"
45,UtahMedian income (dollars)Estimate,"89,168"
46,VermontMedian income (dollars)Estimate,"73,991"
47,VirginiaMedian income (dollars)Estimate,"85,873"
48,WashingtonMedian income (dollars)Estimate,"91,306"
49,West VirginiaMedian income (dollars)Estimate,"54,329"
50,WisconsinMedian income (dollars)Estimate,"70,996"
51,WyomingMedian income (dollars)Estimate,"70,042"
52,Puerto RicoMedian income (dollars)Estimate,"24,112"

In [30]:
# Read CSV File for 2021
census_data_21 = Path("Resources/census_data_2021.csv")
census_df_21 = pd.read_csv(census_data_21)

# Display the DataFrame
census_df_21.head()

# Keep only columns that contain "Median income (dollars)!!Estimate" in their name
filtered_columns_21 = [col for col in census_df_21.columns if "Median income (dollars)!!Estimate" in col or "Label (Grouping)" in col]

# Create a new DataFrame with only the filtered columns
census_df_filtered_21 = census_df_21[filtered_columns_21]

# Check the filtered DataFrame
census_df_filtered_21.head()

# Transpose DF
census_df_filtered_t_21 = census_df_filtered_21.transpose()
census_df_filtered_t_21.columns = census_df_filtered_t_21.iloc[0]
census_df_filtered_t_21.head()

# Rename Columns by taking out extra characters
census_renamed_21 = census_df_filtered_21.rename(columns=lambda col: col.replace('!!', ''))
census_renamed_21

#transpose
census_t_21 = census_renamed_21.transpose()
census_t_21.head()

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
Label (Grouping),HOUSEHOLD INCOME BY RACE AND HISPANIC OR LATIN...,2021 Median Household Income,One race--,White,Black or African American,American Indian and Alaska Native,Asian,Native Hawaiian and Other Pacific ...,Some other race,Two or more races,...,2 earners,3 or more earners,NONFAMILY HOUSEHOLDS,Nonfamily households,Female householder,Living alone,Not living alone,Male householder,Living alone,Not living alone
AlabamaMedian income (dollars)Estimate,NaN,"53,913",NaN,"62,496","36,058","48,139","84,745","58,696","40,722","52,917",...,"96,666","126,938",NaN,"30,575","25,681","23,830","50,057","37,906","33,185","60,439"
AlaskaMedian income (dollars)Estimate,NaN,"77,845",NaN,"82,051","61,411","50,892","80,106","66,513","64,187","87,839",...,"119,004","142,279",NaN,"48,081","43,284","38,236","97,423","50,681","39,969","85,723"
ArizonaMedian income (dollars)Estimate,NaN,"69,056",NaN,"73,604","54,765","42,397","91,289","89,655","59,089","60,630",...,"104,046","128,340",NaN,"43,690","40,240","33,828","72,953","47,966","40,373","78,773"
ArkansasMedian income (dollars)Estimate,NaN,"52,528",NaN,"56,707","36,292","48,188","85,380","47,838","46,382","54,916",...,"90,772","113,894",NaN,"29,499","27,159","24,393","50,959","31,920","27,482","54,393"

In [31]:
census_t_21[1]

Label (Grouping)                                       2021 Median Household Income
AlabamaMedian income (dollars)Estimate                                       53,913
AlaskaMedian income (dollars)Estimate                                        77,845
ArizonaMedian income (dollars)Estimate                                       69,056
ArkansasMedian income (dollars)Estimate                                      52,528
CaliforniaMedian income (dollars)Estimate                                    84,907
ColoradoMedian income (dollars)Estimate                                      82,254
ConnecticutMedian income (dollars)Estimate                                   83,771
DelawareMedian income (dollars)Estimate                                      71,091
District of ColumbiaMedian income (dollars)Estimate                          90,088
FloridaMedian income (dollars)Estimate                                       63,062
GeorgiaMedian income (dollars)Estimate                                       66,559
HawaiiMedian income (dollars)Estimate                                        84,857
IdahoMedian income (dollars)Estimate                                         66,474
IllinoisMedian income (dollars)Estimate                                      72,205
IndianaMedian income (dollars)Estimate                                       62,743
IowaMedian income (dollars)Estimate                                          65,600
KansasMedian income (dollars)Estimate                                        64,124
KentuckyMedian income (dollars)Estimate                                      55,573
LouisianaMedian income (dollars)Estimate                                     52,087
MaineMedian income (dollars)Estimate                                         64,767
MarylandMedian income (dollars)Estimate                                      90,203
MassachusettsMedian income (dollars)Estimate                                 89,645
MichiganMedian income (dollars)Estimate                                      63,498
MinnesotaMedian income (dollars)Estimate                                     77,720
MississippiMedian income (dollars)Estimate                                   48,716
MissouriMedian income (dollars)Estimate                                      61,847
MontanaMedian income (dollars)Estimate                                       63,249
NebraskaMedian income (dollars)Estimate                                      66,817
NevadaMedian income (dollars)Estimate                                        66,274
New HampshireMedian income (dollars)Estimate                                 88,465
New JerseyMedian income (dollars)Estimate                                    89,296
New MexicoMedian income (dollars)Estimate                                    53,992
New YorkMedian income (dollars)Estimate                                      74,314
North CarolinaMedian income (dollars)Estimate                                61,972
North DakotaMedian income (dollars)Estimate                                  66,519
OhioMedian income (dollars)Estimate                                          62,262
OklahomaMedian income (dollars)Estimate                                      55,826
OregonMedian income (dollars)Estimate                                        71,562
PennsylvaniaMedian income (dollars)Estimate                                  68,957
Rhode IslandMedian income (dollars)Estimate                                  74,008
South CarolinaMedian income (dollars)Estimate                                59,318
South DakotaMedian income (dollars)Estimate                                  66,143
TennesseeMedian income (dollars)Estimate                                     59,695
TexasMedian income (dollars)Estimate                                         66,963
UtahMedian income (dollars)Estimate                                          79,449
VermontMedian income (dollars)Estimate                                       72,431
VirginiaMedian income (dollars)Estimate                                      80,963
WashingtonMedian income (dollars)Estimate                                    84,247
West VirginiaMedian income (dollars)Estimate                                 51,248
WisconsinMedian income (dollars)Estimate                                     67,125
WyomingMedian income (dollars)Estimate                                       65,204
Puerto RicoMedian income (dollars)Estimate                                   22,237
Name: 1, dtype: object

In [32]:
census_21_households = census_t_21[1].reset_index()

In [33]:
census_21_households.columns = census_21_households.iloc[0]
census_21_households = census_21_households[1:]

In [34]:
census_21_households

,Label (Grouping),2021 Median Household Income
1,AlabamaMedian income (dollars)Estimate,"53,913"
2,AlaskaMedian income (dollars)Estimate,"77,845"
3,ArizonaMedian income (dollars)Estimate,"69,056"
4,ArkansasMedian income (dollars)Estimate,"52,528"
5,CaliforniaMedian income (dollars)Estimate,"84,907"
6,ColoradoMedian income (dollars)Estimate,"82,254"
7,ConnecticutMedian income (dollars)Estimate,"83,771"
8,DelawareMedian income (dollars)Estimate,"71,091"
9,District of ColumbiaMedian income (dollars)Est...,"90,088"
10,FloridaMedian income (dollars)Estimate,"63,062"
11,GeorgiaMedian income (dollars)Estimate,"66,559"
12,HawaiiMedian income (dollars)Estimate,"84,857"
13,IdahoMedian income (dollars)Estimate,"66,474"
14,IllinoisMedian income (dollars)Estimate,"72,205"
15,IndianaMedian income (dollars)Estimate,"62,743"
16,IowaMedian income (dollars)Estimate,"65,600"
17,KansasMedian income (dollars)Estimate,"64,124"
18,KentuckyMedian income (dollars)Estimate,"55,573"
19,LouisianaMedian income (dollars)Estimate,"52,087"
20,MaineMedian income (dollars)Estimate,"64,767"
21,MarylandMedian income (dollars)Estimate,"90,203"
22,MassachusettsMedian income (dollars)Estimate,"89,645"
23,MichiganMedian income (dollars)Estimate,"63,498"
24,MinnesotaMedian income (dollars)Estimate,"77,720"
25,MississippiMedian income (dollars)Estimate,"48,716"
26,MissouriMedian income (dollars)Estimate,"61,847"
27,MontanaMedian income (dollars)Estimate,"63,249"
28,NebraskaMedian income (dollars)Estimate,"66,817"
29,NevadaMedian income (dollars)Estimate,"66,274"
30,New HampshireMedian income (dollars)Estimate,"88,465"
31,New JerseyMedian income (dollars)Estimate,"89,296"
32,New MexicoMedian income (dollars)Estimate,"53,992"
33,New YorkMedian income (dollars)Estimate,"74,314"
34,North CarolinaMedian income (dollars)Estimate,"61,972"
35,North DakotaMedian income (dollars)Estimate,"66,519"
36,OhioMedian income (dollars)Estimate,"62,262"
37,OklahomaMedian income (dollars)Estimate,"55,826"
38,OregonMedian income (dollars)Estimate,"71,562"
39,PennsylvaniaMedian income (dollars)Estimate,"68,957"
40,Rhode IslandMedian income (dollars)Estimate,"74,008"
41,South CarolinaMedian income (dollars)Estimate,"59,318"
42,South DakotaMedian income (dollars)Estimate,"66,143"
43,TennesseeMedian income (dollars)Estimate,"59,695"
44,TexasMedian income (dollars)Estimate,"66,963"
45,UtahMedian income (dollars)Estimate,"79,449"
46,VermontMedian income (dollars)Estimate,"72,431"
47,VirginiaMedian income (dollars)Estimate,"80,963"
48,WashingtonMedian income (dollars)Estimate,"84,247"
49,West VirginiaMedian income (dollars)Estimate,"51,248"
50,WisconsinMedian income (dollars)Estimate,"67,125"
51,WyomingMedian income (dollars)Estimate,"65,204"
52,Puerto RicoMedian income (dollars)Estimate,"22,237"

In [36]:
# Merge the first two DataFrames
census_21_22 = pd.merge(census_21_households, census_22_households, on="Label (Grouping)")

# Now merge the result with the third DataFrame
census_21_22_23 = pd.merge(census_21_22, census_23_households, on="Label (Grouping)")

# Check the final merged DataFrame
print(census_21_22_23.head())

0                           Label (Grouping) 2021 Median Household Income_x  \
0     AlabamaMedian income (dollars)Estimate                         53,913
1      AlaskaMedian income (dollars)Estimate                         77,845
2     ArizonaMedian income (dollars)Estimate                         69,056
3    ArkansasMedian income (dollars)Estimate                         52,528
4  CaliforniaMedian income (dollars)Estimate                         84,907

0 2022 Median Household Income 2021 Median Household Income_y
0                       59,674                         62,212
1                       88,121                         86,631
2                       74,568                         77,315
3                       55,432                         58,700
4                       91,551                         95,521

In [37]:
census_21_22_23

,Label (Grouping),2021 Median Household Income_x,2022 Median Household Income,2021 Median Household Income_y
0,AlabamaMedian income (dollars)Estimate,"53,913","59,674","62,212"
1,AlaskaMedian income (dollars)Estimate,"77,845","88,121","86,631"
2,ArizonaMedian income (dollars)Estimate,"69,056","74,568","77,315"
3,ArkansasMedian income (dollars)Estimate,"52,528","55,432","58,700"
4,CaliforniaMedian income (dollars)Estimate,"84,907","91,551","95,521"
5,ColoradoMedian income (dollars)Estimate,"82,254","89,302","92,911"
6,ConnecticutMedian income (dollars)Estimate,"83,771","88,429","91,665"
7,DelawareMedian income (dollars)Estimate,"71,091","82,174","81,361"
8,District of ColumbiaMedian income (dollars)Est...,"90,088","101,027","108,210"
9,FloridaMedian income (dollars)Estimate,"63,062","69,303","73,311"
10,GeorgiaMedian income (dollars)Estimate,"66,559","72,837","74,632"
11,HawaiiMedian income (dollars)Estimate,"84,857","92,458","95,322"
12,IdahoMedian income (dollars)Estimate,"66,474","72,785","74,942"
13,IllinoisMedian income (dollars)Estimate,"72,205","76,708","80,306"
14,IndianaMedian income (dollars)Estimate,"62,743","66,785","69,477"
15,IowaMedian income (dollars)Estimate,"65,600","69,588","71,433"
16,KansasMedian income (dollars)Estimate,"64,124","68,925","70,333"
17,KentuckyMedian income (dollars)Estimate,"55,573","59,341","61,118"
18,LouisianaMedian income (dollars)Estimate,"52,087","55,416","58,229"
19,MaineMedian income (dollars)Estimate,"64,767","69,543","73,733"
20,MarylandMedian income (dollars)Estimate,"90,203","94,991","98,678"
21,MassachusettsMedian income (dollars)Estimate,"89,645","94,488","99,858"
22,MichiganMedian income (dollars)Estimate,"63,498","66,986","69,183"
23,MinnesotaMedian income (dollars)Estimate,"77,720","82,338","85,086"
24,MississippiMedian income (dollars)Estimate,"48,716","52,719","54,203"
25,MissouriMedian income (dollars)Estimate,"61,847","64,811","68,545"
26,MontanaMedian income (dollars)Estimate,"63,249","67,631","70,804"
27,NebraskaMedian income (dollars)Estimate,"66,817","69,597","74,590"
28,NevadaMedian income (dollars)Estimate,"66,274","72,333","76,364"
29,New HampshireMedian income (dollars)Estimate,"88,465","89,992","96,838"
30,New JerseyMedian income (dollars)Estimate,"89,296","96,346","99,781"
31,New MexicoMedian income (dollars)Estimate,"53,992","59,726","62,268"
32,New YorkMedian income (dollars)Estimate,"74,314","79,557","82,095"
33,North CarolinaMedian income (dollars)Estimate,"61,972","67,481","70,804"
34,North DakotaMedian income (dollars)Estimate,"66,519","71,970","76,525"
35,OhioMedian income (dollars)Estimate,"62,262","65,720","67,769"
36,OklahomaMedian income (dollars)Estimate,"55,826","59,673","62,138"
37,OregonMedian income (dollars)Estimate,"71,562","75,657","80,160"
38,PennsylvaniaMedian income (dollars)Estimate,"68,957","71,798","73,824"
39,Rhode IslandMedian income (dollars)Estimate,"74,008","81,854","84,972"
40,South CarolinaMedian income (dollars)Estimate,"59,318","64,115","67,804"
41,South DakotaMedian income (dollars)Estimate,"66,143","69,728","71,810"
42,TennesseeMedian income (dollars)Estimate,"59,695","65,254","67,631"
43,TexasMedian income (dollars)Estimate,"66,963","72,284","75,780"
44,UtahMedian income (dollars)Estimate,"79,449","89,168","93,421"
45,VermontMedian income (dollars)Estimate,"72,431","73,991","81,211"
46,VirginiaMedian income (dollars)Estimate,"80,963","85,873","89,931"
47,WashingtonMedian income (dollars)Estimate,"84,247","91,306","94,605"
48,West VirginiaMedian income (dollars)Estimate,"51,248","54,329","55,948"
49,WisconsinMedian income (dollars)Estimate,"67,125","70,996","74,631"
50,WyomingMedian income (dollars)Estimate,"65,204","70,042","72,415"
51,Puerto RicoMedian income (dollars)Estimate,"22,237","24,112","25,621"